#ifndef CONFIG_DEFAULTS_H
#define CONFIG_DEFAULTS_H

/* Configuration Defaults */
const int CONFIG_DEFAULT_CLIP_COPY          = 1;
const int CONFIG_DEFAULT_CLIP_SELECT        = 0;
const int CONFIG_DEFAULT_CLIP_PERSISTANCE   = 1;
const int CONFIG_DEFAULT_CLIP_HIST_REVERSE  = 0;
const int CONFIG_DEFAULT_CLIP_HIST_ITEMS    = 20;
const int CONFIG_DEFAULT_CLIP_LABEL_LENGTH   = 20;
const int CONFIG_DEFAULT_CLIP_TRIM_WS       = 0;
const int CONFIG_DEFAULT_CLIP_NL            = 0;
const int CONFIG_DEFAULT_CLIP_COMFIRM_CLEAR = 1;

#endif
